# Generated by Django 3.2.8 on 2021-10-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('content', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('actions', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('isClickable', models.CharField(max_length=50)),
                ('isDisabled', models.CharField(max_length=50)),
                ('resizeable', models.CharField(max_length=50)),
                ('beforeStart', models.CharField(max_length=50)),
                ('afterEnd', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
