# Generated by Django 3.2.8 on 2021-10-14 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_auto_20211014_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='end',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start',
            field=models.CharField(max_length=90),
        ),
    ]
